### ISSUE TITLE
请问 matlab的版本有要求吗

### ISSUE THREAD

**Issue by EggAgainstStone** [sjtu-jq/Image-registration#1]
您好， 我刚好在做一个 红外图像和可见光图像匹配的功能。 目前情况看来，红外图像要小于可见光，

**Comment by EggAgainstStone** [comment]
我能通过这个算法 找出红外图像在可见光中的位置吗？

**Comment by sjtu-jq** [comment]
> 您好， 我刚好在做一个 红外图像和可见光图像匹配的功能。 目前情况看来，红外图像要小于可见光，

代码里面是将红外和可见光图像预处理了，输入图像时最好是先输入红外，再输入可见光，其次如果红外和可见光图像尺度不同，可以调节cp_registration函数中zoom+和zoom-的值进行降采样设置，匹配输出的结果为图像之间的投影变换矩阵。
此外，本代码对matlab2015-2020均是可以成功运行的，如果不需要并行计算，可以修改cp_cornerdetection函数和cp_descriptior函数中的parfor为for。

**Comment by YangTao-AI** [comment]
@sjtu-jq 请问如何调节cp_registration函数中zoom+和zoom-的值?

**Comment by sjtu-jq** [comment]
> @sjtu-jq 请问如何调节cp_registration函数中zoom+和zoom-的值?

zoom参数是用来图像降采样以后提取SIFT描述符的，它的含义是红外和可见光调为相同的高度分辨率后，相同物体所占的像素面积比（与尺度一词的概念差不多）；当红外和可见光图像调为相同高度分辨率后，视野相同，则zoom为1，zoom+和-就设为0（即视野没有缩放）；如果红外视野比可见光要要窄时，两者调为相同高度分辨率后，可见光里面的物体所占的像素面积就要比红外的要小，所以就要调整可见光图像的描述符采样尺度（设置zoom+的值即可，每增加1，则可见光采样时变大1+0.5*zoom+倍）；zoom-则与之相反。zoom+和-的值和越大，则提取描述符的次数就越多，运行时间越长。

**Comment by YangTao-AI** [comment]
@sjtu-jq 你好，我的热红外图像是384*288，RGB是1080p，没有做任何设置，直接跑你的程序，有些图像能够融合好，有些融合不正确，发现是特征匹配的时候不太对，我现在的疑问是是否一定需要调整为相同分辨率，另外设置zoom+的值有没有什么经验呢？设置多大为好？或者还有没有其它超参数需要更改？麻烦指教下。

**Comment by sjtu-jq** [comment]
> @sjtu-jq 你好，我的热红外图像是384*288，RGB是1080p，没有做任何设置，直接跑你的程序，有些图像能够融合好，有些融合不正确，发现是特征匹配的时候不太对，我现在的疑问是是否一定需要调整为相同分辨率，另外设置zoom+的值有没有什么经验呢？设置多大为好？或者还有没有其它超参数需要更改？麻烦指教下。

关于本算法的理论原理，以及各个参数的设置问题，你可以仔细阅读参考文献，里面都有提到，是本人7月份录用的文章。关于你说的配准有时好，有时不好的问题，这是因为红外和可见光图像的配准难度确实很大，尤其是分辨率相差太大的情况下（算法默认是把可见光图像调整为红外分辨率的，阅读main文件容易发现这个调整代码）。如果还有其它问题，欢迎在新issue里面提出。
