### ISSUE TITLE
大景深，大范围，大视差红外可见光图像配准

### ISSUE THREAD

**Issue by ysingfun** [sjtu-jq/Image-registration#2]
很感谢你的工作！！！
我在使用是你们的算法测试自己的数据时发现匹配结果很差，如下：
![屏幕截图 2021-09-11 213234](https://user-images.githubusercontent.com/37376098/132949587-2afa1a2b-8793-4803-a659-abbe0699efad.png)
图片尺寸687x693,距离应该在30m左右

**Comment by sjtu-jq** [comment]
你好，我们的算法主要是用于电力设备的热红外图像和可见光图像配准的，对于你这类的夜间可见光和红外图像数据集配准，我们并未做相关优化，你可以尝试一些图像亮度或细节增强之类的处理使得可见光图像细节更加丰富。
